#!/usr/bin/env python3
# -*- coding: utf-8 -*-

'a test module'

__author__ = 'kevin'

import sys


def test():
    args = sys.argv
    argLen = len(args)
    if argLen == 1:
        print("Hello,This is Test")
    elif argLen == 2:
        print('Hello,This is ' + args[1])
    else:
        print('Hello，Args Too Much')


if __name__ == '__main__':
    test()
